
	

all:   data.h process.c  states.c  exportFiles.c  errors.c utility_funcs.c help_function.c parse.c operations.c tables.c memory.c firstround.c secondround.c main.c
	gcc -ansi -Wall -pedantic -g data.h process.c states.c   exportFiles.c errors.c utility_funcs.c help_function.c parse.c operations.c tables.c  memory.c secondround.c firstround.c main.c -o main -lm